### ISSUE TITLE
Remove placeholders from mkdocs

### ISSUE THREAD

**Issue by jason-fox** [ramp-eu/JS2SF#5]
`mkdocs.yml` currently starts as follows:

```yml
site_name: <site-name>
site_url: https://<site-url>
repo_url: https://github.com/<repo_url>
site_description: RAMP Documentation
```

remove the placeholders and describe what the component actually does.
